-- Datos de demostración (origen='seed') para que el tablero no arranque vacío.
-- Fechas relativas a "hoy" para que la tendencia semanal siempre tenga datos.

INSERT INTO observaciones
    (created_at, canal, servicio_obra, lugar, fecha_obs, tipo, personal, num_personas,
     categoria, subitem, observacion, acciones_correctivas, severidad, prioridad, origen, estado)
VALUES
    (datetime('now','-27 days'), 'whatsapp', 'Equipo de Torre WO-14', 'Boca de pozo PT-112', date('now','-27 days'), 'inseguro', 'propio', 2,
     4, 'b', 'Manguera hidráulica con la malla exterior pelada en la unidad de llaves, pérdida visible de fluido.', 'Se detuvo la maniobra y se reemplazó la manguera antes de continuar.', 3, 'rojo', 'seed', 'cerrada'),
    (datetime('now','-26 days'), 'whatsapp', 'Batería B-7', 'Playa de tanques', date('now','-26 days'), 'inseguro', 'contratista', 1,
     3, 'f', 'Operario trabajando sobre el techo del tanque sin arnés colocado.', 'Se le pidió que baje y se colocó el arnés con línea de vida.', 4, 'rojo', 'seed', 'en_revision'),
    (datetime('now','-25 days'), 'whatsapp', 'Planta de Tratamiento Norte', 'Sala de bombas', date('now','-25 days'), 'seguro', 'propio', 3,
     1, 'd', 'El equipo aplicó bloqueo y etiquetado correctamente antes de intervenir la bomba P-203.', 'Se reconoció la buena práctica en la charla diaria.', 1, 'verde', 'seed', 'cerrada'),
    (datetime('now','-24 days'), 'whatsapp', 'Equipo de Pulling P-03', 'Locación LC-45', date('now','-24 days'), 'inseguro', 'propio', 1,
     6, 'd', 'Caños de maniobra acopiados sin calzas ni topes, riesgo de rodamiento.', 'Se calzaron los tubos y se ordenó el sector de acopio.', 2, 'amarillo', 'seed', 'cerrada'),
    (datetime('now','-22 days'), 'whatsapp', 'Base Operativa', 'Taller de mantenimiento', date('now','-22 days'), 'inseguro', 'propio', 1,
     4, 'c', 'Amoladora usada sin la protección del disco colocada.', 'Se detuvo la tarea y se repuso la protección.', 3, 'rojo', 'seed', 'cerrada'),
    (datetime('now','-21 days'), 'whatsapp', 'Batería B-7', 'Colector de producción', date('now','-21 days'), 'inseguro', 'contratista', 2,
     8, 'b', 'Goteo de petróleo en brida del colector, suelo con hidrocarburo.', 'Se colocó bandeja de contención y se avisó a mantenimiento.', 2, 'amarillo', 'seed', 'en_revision'),
    (datetime('now','-20 days'), 'whatsapp', 'Equipo de Torre WO-14', 'Piso de enganche', date('now','-20 days'), 'seguro', 'propio', 1,
     3, 'a', 'Enganchador con casco, barbijo de tormenta ajustado y arnés en perfectas condiciones.', 'Reconocimiento verbal en el momento.', 1, 'verde', 'seed', 'cerrada'),
    (datetime('now','-19 days'), 'whatsapp', 'Planta de Tratamiento Norte', 'Laboratorio', date('now','-19 days'), 'inseguro', 'propio', 1,
     9, 'a', 'Bidón con producto químico trasvasado sin rótulo ni identificación.', 'Se rotuló el envase y se recordó el procedimiento de trasvase.', 2, 'amarillo', 'seed', 'cerrada'),
    (datetime('now','-18 days'), 'whatsapp', 'Logística', 'Ruta de acceso a LC-45', date('now','-18 days'), 'inseguro', 'contratista', 1,
     7, 'a', 'Camioneta de contratista circulando a alta velocidad en zona de locación.', 'Se informó al supervisor del contratista.', 3, 'rojo', 'seed', 'nueva'),
    (datetime('now','-17 days'), 'whatsapp', 'Base Operativa', 'Pañol', date('now','-17 days'), 'inseguro', 'propio', 1,
     6, 'b', 'Banco de trabajo con herramientas sueltas y restos de trapos con solvente.', 'Se ordenó el banco y se descartaron los trapos en el cesto correspondiente.', 1, 'verde', 'seed', 'cerrada'),
    (datetime('now','-15 days'), 'whatsapp', 'Equipo de Pulling P-03', 'Locación LC-45', date('now','-15 days'), 'inseguro', 'propio', 4,
     5, 'b', 'Se inició maniobra de izaje sin completar el permiso de trabajo correspondiente.', 'Se detuvo la maniobra hasta completar el permiso.', 4, 'rojo', 'seed', 'en_revision'),
    (datetime('now','-14 days'), 'whatsapp', 'Batería B-7', 'Playa de tanques', date('now','-14 days'), 'seguro', 'propio', 2,
     5, 'b', 'Cuadrilla respetó al pie de la letra el procedimiento de medición de tanques con detector de gases.', 'Felicitación en la reunión de seguridad semanal.', 1, 'verde', 'seed', 'cerrada'),
    (datetime('now','-13 days'), 'whatsapp', 'Planta Compresora Sur', 'Sala de compresores', date('now','-13 days'), 'inseguro', 'propio', 1,
     3, 'b', 'Operador recorriendo la sala sin protección auditiva.', 'Se le entregaron protectores y se repuso el cartel de uso obligatorio.', 2, 'amarillo', 'seed', 'cerrada'),
    (datetime('now','-12 days'), 'whatsapp', 'Equipo de Torre WO-14', 'Subestructura', date('now','-12 days'), 'inseguro', 'contratista', 2,
     2, 'c', 'Ayudante con la mano en punto de atrapamiento entre cuñas y mesa rotary durante la maniobra.', 'Se detuvo la maniobra y se reubicó al ayudante fuera de la línea de fuego.', 4, 'rojo', 'seed', 'nueva'),
    (datetime('now','-11 days'), 'whatsapp', 'Base Operativa', 'Oficinas', date('now','-11 days'), 'inseguro', 'propio', 1,
     10, 'a', 'Matafuego del pasillo con carga vencida el mes pasado.', 'Se envió a recargar y se colocó uno de reemplazo.', 2, 'amarillo', 'seed', 'cerrada'),
    (datetime('now','-10 days'), 'whatsapp', 'Logística', 'Playa de maniobras', date('now','-10 days'), 'inseguro', 'propio', 2,
     7, 'b', 'Semirremolque estacionado sin calzas en pendiente leve.', 'Se colocaron calzas y se habló con el chofer.', 2, 'amarillo', 'seed', 'cerrada'),
    (datetime('now','-9 days'),  'whatsapp', 'Planta de Tratamiento Norte', 'Pileta API', date('now','-9 days'), 'inseguro', 'contratista', 3,
     8, 'b', 'Venteo de gas con olor intenso cerca de la pileta API durante la limpieza.', 'Se suspendió la tarea y se midió atmósfera antes de continuar.', 3, 'rojo', 'seed', 'en_revision'),
    (datetime('now','-8 days'),  'whatsapp', 'Equipo de Pulling P-03', 'Locación LC-38', date('now','-8 days'), 'seguro', 'propio', 3,
     1, 'e', 'Cuadrilla cambió de herramienta al notar que la llave no era la adecuada para el diámetro.', 'Se destacó la reacción correcta en la charla de 5 minutos.', 1, 'verde', 'seed', 'cerrada'),
    (datetime('now','-7 days'),  'whatsapp', 'Batería B-7', 'Sala de calderas', date('now','-7 days'), 'inseguro', 'propio', 1,
     10, 'a', 'Escalera fija de acceso con peldaño flojo y sin baranda en el último tramo.', 'Se señalizó y se pidió reparación a mantenimiento.', 3, 'rojo', 'seed', 'nueva'),
    (datetime('now','-6 days'),  'whatsapp', 'Base Operativa', 'Comedor', date('now','-6 days'), 'inseguro', 'propio', 1,
     6, 'c', 'Cables de alargue cruzando el pasillo del comedor a la altura del piso.', 'Se reubicó el tendido por el lateral.', 1, 'verde', 'seed', 'cerrada'),
    (datetime('now','-5 days'),  'whatsapp', 'Equipo de Torre WO-14', 'Boca de pozo PT-118', date('now','-5 days'), 'inseguro', 'propio', 2,
     2, 'e', 'Dos operarios levantando a mano un trozo de varilla que requería aparejo, sobreesfuerzo evidente.', 'Se detuvo la tarea y se usó el aparejo del equipo.', 2, 'amarillo', 'seed', 'cerrada'),
    (datetime('now','-5 days'),  'whatsapp', 'Planta Compresora Sur', 'Perímetro', date('now','-5 days'), 'inseguro', 'contratista', 1,
     8, 'd', 'Viento fuerte con voladura de chapas sueltas del obrador del contratista.', 'Se aseguraron las chapas y se suspendió trabajo en altura.', 3, 'rojo', 'seed', 'en_revision'),
    (datetime('now','-4 days'),  'whatsapp', 'Logística', 'Depósito de químicos', date('now','-4 days'), 'inseguro', 'propio', 1,
     9, 'b', 'No se encontraban las hojas de seguridad (FDS) de los inhibidores en el gabinete del depósito.', 'Se imprimieron y repusieron las FDS en el gabinete.', 2, 'amarillo', 'seed', 'cerrada'),
    (datetime('now','-3 days'),  'whatsapp', 'Equipo de Pulling P-03', 'Locación LC-38', date('now','-3 days'), 'inseguro', 'propio', 1,
     3, 'd', 'Operario manipulando cable de acero sin guantes.', 'Se detuvo la tarea y se colocaron guantes de descarne.', 2, 'amarillo', 'seed', 'nueva'),
    (datetime('now','-2 days'),  'whatsapp', 'Batería B-7', 'Colector de producción', date('now','-2 days'), 'seguro', 'propio', 2,
     1, 'b', 'Operadores interrumpieron la tarea al detectar olor a gas y avisaron a sala de control antes de continuar.', 'Reconocimiento y registro como reacción positiva.', 1, 'verde', 'seed', 'cerrada'),
    (datetime('now','-2 days'),  'whatsapp', 'Planta de Tratamiento Norte', 'Sala de bombas', date('now','-2 days'), 'inseguro', 'contratista', 2,
     5, 'c', 'Personal nuevo del contratista no comprendía el procedimiento de bloqueo; lo ejecutaba incompleto.', 'Se reentrenó en el momento con el supervisor.', 3, 'rojo', 'seed', 'nueva'),
    (datetime('now','-1 days'),  'whatsapp', 'Equipo de Torre WO-14', 'Piso de trabajo', date('now','-1 days'), 'inseguro', 'propio', 3,
     4, 'a', 'Llave de fuerza improvisada con caño de extensión no homologado.', 'Se retiró la extensión y se pidió la herramienta correcta al pañol.', 3, 'rojo', 'seed', 'nueva'),
    (datetime('now','-1 days'),  'whatsapp', 'Base Operativa', 'Estacionamiento', date('now','-1 days'), 'inseguro', 'propio', 1,
     7, 'b', 'Camioneta con neumático delantero visiblemente desgastado en la banda de rodadura.', 'Se sacó de servicio hasta el cambio de cubierta.', 2, 'amarillo', 'seed', 'nueva'),
    (datetime('now','-8 hours'), 'whatsapp', 'Planta Compresora Sur', 'Sala de compresores', date('now'), 'inseguro', 'propio', 1,
     11, NULL, 'Iluminación de emergencia no encendió durante el corte de energía programado.', 'Se informó a electricidad, pendiente de reparación.', 2, 'amarillo', 'seed', 'nueva'),
    (datetime('now','-3 hours'), 'whatsapp', 'Batería B-7', 'Playa de tanques', date('now'), 'seguro', 'contratista', 2,
     3, 'f', 'Contratista utilizando doble cabo de vida para trabajo en altura sobre tanque, maniobra impecable.', 'Se felicitó al personal y a su supervisor.', 1, 'verde', 'seed', 'nueva');
